# conda env create -f dev-environment.yml
name: pytao-dev
channels:
  - conda-forge
dependencies:
  - python==3.11
# Developer
  - openPMD-beamphysics
  - numpydoc
  - bokeh
  - pytest
  - pytest-cov
  - jupyterlab>3
  - ipywidgets
  - matplotlib
  - pygments
  - mkdocs==1.5.2 # pin because of a bug in the latest: ModuleNotFoundError: No module named 'mkdocs.tests'
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python

