# conda env create -f dev-environment.yml
name: pytao-dev
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - openPMD-beamphysics
  - numpydoc
  - bmad
  - bokeh
  - jupyterlab>3
  - ipywidgets
  - matplotlib
  - numpy
  - h5py
  - pexpect
  # Developer
  - pygments
  - pytest
  - pytest-cov
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python
  - pip
  - pip:
      # Install pytao from here.
      - .
