# conda env create -f dev-environment.yml
name: pytao-dev
channels:
  - conda-forge
dependencies:
  - python==3.12
# Developer
  - openPMD-beamphysics
  - numpydoc
  - bokeh
  - pytest
  - pytest-cov
  - jupyterlab>3
  - ipywidgets
  - matplotlib
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter==0.24.6
  - mkdocstrings-python

