# conda env create -f environment.yml
name: pytao-dev
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - ipykernel
  - ipywidgets
  - jupyterlab
  - bmad
  - openPMD-beamphysics
  # PyTao release:
  - pytao
  # or PytTao Developer:
#  - pip:
#    - git+git://github.com/bmad-sim/pytao
