
name: Publish Documentation

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    if: ${{ github.repository == 'bmad-sim/pytao' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          activate-environment: pytao-dev
          environment-file: dev-environment.yml
      - name: Pin MkDocs to 1.5.2
        shell: bash -l {0}
        run: |
          mamba list
          mamba install -c conda-forge mkdocs==1.5.2 --yes
      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build
          zip -r pytao-examples.zip docs/examples/
          mv pytao-examples.zip ./site/assets/.
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/